### DISCUSSION TITLE
adw::PasswordEntryRow is missing styles

### DISCUSSION THREAD

**Discussion by 66Leo66** [Relm4/Relm4#443] [Q&A] [answered]
I'm encountering issues with the `PasswordEntryRow` appearance of `relm4`. As shown in the screenshot below, the current appearance has sharp edges and lacks shadows.

![image](https://user-images.githubusercontent.com/33322229/230035232-17a92a43-7bc9-4f2e-baa1-b5cba36763a4.png)

However, according to [libadwaita's documentation](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.PasswordEntryRow.html), I was expecting the following appearance, which I managed to achieve using `gtk-rs`, but unfortunately lost the code:

![image](https://user-images.githubusercontent.com/33322229/230033876-0bfaacb7-3d75-4c33-9d9a-fac6a36d6221.png)

The main differences between the two appearances are rounded corners and shadows. The current appearance looks odd, especially when not focused, as it blends in with the background.

I've adapted my code from the `relm` book's sample, snippets of which are provided below.

```rust main.rs
// main.rs
view! {
        #[root]
        adw::Window {
            // set_default_size: (540, 100),
            set_default_width: 540,
            set_vexpand: true,

            gtk::Box {
                set_orientation: gtk::Orientation::Vertical,
                adw::HeaderBar {
                    set_show_end_title_buttons: true,
                    #[wrap(Some)]
                    set_title_widget = &adw::WindowTitle {
                        set_title: "Simple example",
                        set_subtitle: "relm4",
                    },
                },
                gtk::Box {
                    set_orientation: gtk::Orientation::Vertical,
                    set_spacing: 4,
                    set_margin_all: 8,

                    gtk::ListBox {
                        adw::PasswordEntryRow {
                            set_title: "Password",
                        },
                    },
                    

                    gtk::Button {
                        set_label: "+",
                        connect_clicked => Msg::Increment,
                    },

                    gtk::Button {
                        set_label: "-",
                        connect_clicked => Msg::Decrement,
                    },

                    gtk::Label {
                        #[watch]
                        set_label: &format!("Num: {}", model.counter),
                        set_margin_all: 5,
                    }
                }
            }
        }
    }
```

```toml Cargo.toml
# Cargo.toml
[package]
name = "my-project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
relm4 = { version = "0.5.0", features = ["macros", "libadwaita", "gnome_43"] }
relm4-components = "0.5.0"
```
