### DISCUSSION TITLE
Relm 0.6 apps can't be built with GitHub Actions / Ubuntu 22.04 runners

### DISCUSSION THREAD

**Discussion by chriskilding** [Relm4/Relm4#495] [Q&A] [answered]
When I attempt to build a Relm4 app which uses Relm4 0.6.0 on the standard GitHub Actions Ubuntu 22.04 runner, `cargo build` fails with the following error:

```
cargo:warning=`PKG_CONFIG_ALLOW_SYSTEM_CFLAGS="1" "pkg-config" "--libs" "--cflags" "glib-2.0" "glib-2.0 >= 2.74"` did not exit successfully: exit status: 1
  error: could not find system library 'glib-2.0' required by the 'glib-sys' crate

  --- stderr
  Requested 'glib-2.0 >= 2.74' but version of GLib is 2.72.4
```

Extract of Cargo.toml:

```toml
[package]
edition = '2021'
# ...

[dependencies]
relm4 = { version = "0.6.0", features = ["libadwaita", "gnome_42"] }
relm4-components = "0.6.0"
relm4-macros = "0.6.0"
relm4-icons = "0.6.0"
rust-i18n = "2.0.0"
tracker = "0.2.1"
log = "0.4.19"
```

GitHub Actions workflow:

```yaml
name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
```

It appears that somewhere down the Relm4 dependency tree, there is a dependency on a newer version of Glib than Ubuntu 22.04 can provide.

This problem effectively prevents using Ubuntu 22.04 (and therefore at this time GitHub Actions) as a CI build environment for Relm4 apps. Therefore it would be very helpful if this could be fixed, or a solution could be found! (For example, is it possible to build using a bundled copy of Glib rather than the system version, so that we can control the Glib version?)

**Comment by AaronErhardt** [comment]
This is weird. Relm4 just passes the GNOME 42 feature to the gtk4 crate ([source](https://github.com/Relm4/Relm4/blob/main/relm4/Cargo.toml#L36C1-L36C28)) and then gtk4 enables a couple of features itself, most notably gio v2.72 ([source](https://github.com/gtk-rs/gtk4-rs/blob/master/gtk4/Cargo.toml#L35)). This means that just looking at those features, glib 2.72 should indeed be enough to compile Relm4.

Do you have any other dependencies such as libadwaita that are also compiled?

**Reply by chriskilding** [reply]
Yes, `libadwaita` is also used. Are you thinking that it might depend on a different Glib version than the other GTK libraries?

I've also updated the question with the Cargo.toml and GitHub Actions definition I tried to use, in case that is helpful.

**Reply by chriskilding** [reply]
The 'slow train' approach would be to wait for Ubuntu 24.04 LTS to be released and then made available on GitHub Actions. 24.04 would by definition have a system GLib new enough to satisfy the minimum version requirement, so at that point the Rust build would start working.

(If we don't come up with any ideas for a fix, this does at least provide an option of last resort, albeit not a great one)

**Reply by AaronErhardt** [reply]
I've just found the cause and it's kind of embarrassing :facepalm:

I think at some point during the development I thought that GNOME 43 might be a good baseline and activated "gnome_43" by default: https://github.com/Relm4/Relm4/blob/v0.6.0/relm4/Cargo.toml#L27C23-L27C31

I think this should be reverted, at least for the upcoming 0.7 version to avoid more problems like this.

This means you should be able to fix this by using 

```toml
relm4 = { version = "0.6.0", default-features = false, features = ["macros", "libadwaita", "gnome_42"] }
```

**Reply by chriskilding** [reply]
I've tried the fix but unfortunately it has not worked; I get the same error as before.

**Reply by AaronErhardt** [reply]
It looks like `relm4-components` requires `relm4`, but doesn't specify `default-features = false` to it also enables the "gnome_43" feature flag. I've fixed this on the main branch and also reduced the default features of `relm4` to "gnome_42". I'll do a point release probably tomorrow.

**Reply by chriskilding** [reply]
How is the point release coming along? (Is the latest commit 9ef5e34 essentially what will be released?)

**Reply by AaronErhardt** [reply, marked as answer]
Sorry for the delay, 0.6.1 is now published on crates.io.

**Reply by chriskilding** [reply]
Great! I have tried using it and can confirm that a Relm 0.6.1 app now compiles with the (almost) default Rust build workflow for GitHub Actions:

```yml
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get update && sudo apt-get install -y libgtk-4-dev libadwaita-1-dev # the only custom bit, required to satisfy the gtk4-sys and adwaita-sys crate builds
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
```
